### ISSUE TITLE
Why is this repo empty?

### ISSUE THREAD

**Issue by RobbieTheWagner** [formly-js/ember-formly#1]
I'd like to help work on this.

**Comment by kentcdodds** [comment]
Sorry, I never saw this. You and @benoror might be interested in collaborating :-)

**Comment by benoror** [comment]
@rwwagner90 with Angular2 already a RC, being heavily Component-based (just as Ember 2 !!), and the recent release of https://github.com/formly-js/ng2-formly I feel like paving the way for this being a thing :)

**Comment by benoror** [comment]
I like the idea of having a "vanilla JS" / "web components" core lib, and just make an addon for Ember.

There was some kind of initiative some time ago: https://github.com/forms-js

**Comment by RobbieTheWagner** [comment]
@benoror I hadn't really thought anything out, but I'm down to help get some Ember support going. Let me know what you need from me.

**Comment by benoror** [comment]
@rwwagner90 I'm still wrapping my head around Ember, but if I have a real need for this I would be willing to help as well in the future, thanks!

**Comment by RobbieTheWagner** [comment]
Rather than leave this open issue, I'm going to close, now that we've discussed somewhat. Please reach out if you'd like to work together on this, but it is a large undertaking for me to attempt without another person or two interested.

**Comment by benoror** [comment]
Hey @rwwagner90, 

Just wanted to let you know I made a simple draft with an example of what I had in mind for structuring **ember-formly** 🎉 🎈 💥 

Since you showed some interest I hope this helps as a seed for building something more concise and maybe rethinking some of the original ideas behind angular-formly :)

<img width="284" alt="screen shot 2016-06-10 at 23 57 30" src="https://cloud.githubusercontent.com/assets/119117/15983280/9d9c2db0-2f67-11e6-9c35-f1764692e620.png">

<img width="690" alt="screen shot 2016-06-11 at 00 00 28" src="https://cloud.githubusercontent.com/assets/119117/15983278/9496090c-2f67-11e6-8c22-428e3b6e349b.png">

(cc @kentcdodds cheers mate 😄)

**Comment by benoror** [comment]
As pointed in slack (https://embercommunity.slack.com/archives/general/p1465495139002173) there's something already in the works: https://github.com/martndemus/ember-form-for

Maybe having some sort of support for angular-formly-like **arrays** on top of it would be ideal

**Comment by RobbieTheWagner** [comment]
@benoror the guy in charge of ember-form-for mentioned his priorities were a11y and i18n before JSON powered forms. Perhaps we could help out with the JSON side while they work on the rest?

**Comment by benoror** [comment]
gonna close this as I already have some working examples for my personal use-cases. feel free to reopen
